### ISSUE TITLE
Cannot edit players.

### ISSUE THREAD

**Issue by kudosforanuget** [TerraMap/windows#1]
Cannot Edit where players directory is.  It is always looking under AppData for Jason.

**Comment by Jman420** [comment]
Pull Request submitted with fix.  Issue is not where the Player Files are located, but rather how they are named.  See https://github.com/TerraMap/windows/pull/2

**Comment by jasoncoon** [comment]
Fixed in https://github.com/TerraMap/windows/pull/2, thanks @Jman420!  New release is available here: http://terramap.github.io/windows.html
