### ISSUE TITLE
Cant load world anymore

### ISSUE THREAD

**Issue by KillerJWB86** [TerraMap/windows#11]
So everythign was working fine until we beat plantera. Now what i try to load the world i get https://pastebin.com/X6Y4sXJf       Here is the world save if you need it   https://drive.google.com/open?id=1RGXFgdjj5nyOMwEXe6xSEaDLYAzn2GBx 
We killed plantera the same time i had to update to 1.4.0.3 either one could of caused the error.
TerraMap 1.4.4  Terraria Server 1.4.0.3

**Comment by jasoncoon** [comment]
I got the same error.  They released v1.4.0.3 patch, changed the world format slightly.  Should be fixed now: https://terramap.github.io/windows
