### ISSUE TITLE
Terramap is not able to filter content of Dead Man's Chests

### ISSUE THREAD

**Issue by JorgePozoR** [TerraMap/windows#12]
Hi.

There is a new kind of chest in 1.4 named Dead Man's Chests (a trapped kind of chest spawning in the jungle).

Terramap is able to open and show its contents with the left click flawlessly, but using the Block filtering option for searching for content, they are not highlighted when choosing a matching content like regular chests.

For example, I was looking for some Hermes Boots. Choosing the Hermes Boots in the Highlight option Terramap highlighted a couple of regular Gold Chests in the junge, yet it failed to highligh a Dead Man's that was much easier to access which also contained said boots.

Thanks

**Comment by JorgePozoR** [comment]
Forgot to mention, using latest terraria build, as of now 1.4.0.3 at steam, and latest Terramap 1.4.5

**Comment by jasoncoon** [comment]
Found the problem, will be fixed in the next release, later today likely.  Thanks!

**Comment by jasoncoon** [comment]
OK, try again with TerraMap v1.4.6?  https://terramap.github.io/windows

**Comment by JorgePozoR** [comment]
Downloading now. Will report asap.

Thanks!

**Comment by JorgePozoR** [comment]
Confirmed fixed on v1.4.6, yay!!!!

Closing now.

Thank you!
