### ISSUE TITLE
Bast Statues inside chests will not be highlighted.

### ISSUE THREAD

**Issue by MattRKing** [TerraMap/windows#13]
As the title states, Bast Statues which are found in gold chests will not highlight when the item is selected.

**Comment by MattRKing** [comment]
Magic Conch as well from what I have seen.

**Comment by jasoncoon** [comment]
Sorry, I can't seem to reproduce this problem.
![image](https://user-images.githubusercontent.com/3598755/82732584-acd69d00-9cd3-11ea-9176-c8b4711b113c.png)

**Comment by jasoncoon** [comment]
I think this might be related to new/different kinds of chests, as in this issue: https://github.com/TerraMap/windows/issues/12  Should be fixed in the next release, hopefully later today.  Thanks!

**Comment by jasoncoon** [comment]
OK, try again with TerraMap v1.4.6?  https://terramap.github.io/windows

**Comment by MattRKing** [comment]
Seems like v1.4.6 has fixed the issue.  Thanks.
