### ISSUE TITLE
Issue loading map

### ISSUE THREAD

**Issue by arkanstigers** [TerraMap/windows#15]
Two of my maps load, but one map refuses. The bar at the bottom reads "reading world header" and hasn't made any progress in a little while.

**Comment by arkanstigers** [comment]
Sorry, I'm having this issue with Terramap Web, not Terramap Windows.

**Comment by jasoncoon** [comment]
No problem, mind creating an issue here: https://github.com/TerraMap/terramap.github.io/issues and/or uploading a world?  Has the world been loaded and saved in the latest version of Terraria v1.4.0.3?
