### ISSUE TITLE
Missing Tile - Locked Desert Chest

### ISSUE THREAD

**Issue by Shorte240** [TerraMap/windows#16]
Scanning through my dungeon to find the biome chests, TerraMap can highlight all but the Locked Desert Chest. It appears as a Golden Chest for some reason.
Attached is an image with the highlighted Locked Desert Chest in red, near a Locked Corruption Chest(right).
![TerraMap Issue](https://user-images.githubusercontent.com/25102928/82738956-a7a93a80-9d33-11ea-861e-8518873f1b98.png)

**Comment by TerraTerra77** [comment]
hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck

**Comment by Shorte240** [comment]
> hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck

Sure thing.
3.3.1.1723894116

**Comment by TerraTerra77** [comment]
> > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> 
> Sure thing.
> 3.3.1.1723894116

can u tell me the world setting too?

**Comment by Shorte240** [comment]
> > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > 
> > 
> > Sure thing.
> > 3.3.1.1723894116
> 
> wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff

I have it set to Master, no idea if that affects whats in the chest.

**Comment by TerraTerra77** [comment]
> > > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > > 
> > > 
> > > Sure thing.
> > > 3.3.1.1723894116
> > 
> > 
> > wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff
> 
> I have it set to Master, no idea if that affects whats in the chest.

is there a chance of not getting  a desert chest in the dungeon?

**Comment by Shorte240** [comment]
> > > > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > > > 
> > > > 
> > > > Sure thing.
> > > > 3.3.1.1723894116
> > > 
> > > 
> > > wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff
> > 
> > 
> > I have it set to Master, no idea if that affects whats in the chest.
> 
> is there a chance of not getting a desert chest in the dungeon?

As far as I know it's highly unlikely. Each world is supposed to have one locked chest for each biome present for a total of 5. You get either the Corruption/Crimson depending on the world too.

**Comment by TerraTerra77** [comment]
> > > > > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > > > > 
> > > > > 
> > > > > Sure thing.
> > > > > 3.3.1.1723894116
> > > > 
> > > > 
> > > > wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff
> > > 
> > > 
> > > I have it set to Master, no idea if that affects whats in the chest.
> > 
> > 
> > is there a chance of not getting a desert chest in the dungeon?
> 
> As far as I know it's highly unlikely. Each world is supposed to have one locked chest for each biome present for a total of 5. You get either the Corruption/Crimson depending on the world too.

ive beaten plantera and the golem, do you have any idea why my dungeon have no desert chest? i tried making new worlds too but when i checked the world map on TerraMap. there werent any

**Comment by Shorte240** [comment]
> > > > > > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > > > > > 
> > > > > > 
> > > > > > Sure thing.
> > > > > > 3.3.1.1723894116
> > > > > 
> > > > > 
> > > > > wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff
> > > > 
> > > > 
> > > > I have it set to Master, no idea if that affects whats in the chest.
> > > 
> > > 
> > > is there a chance of not getting a desert chest in the dungeon?
> > 
> > 
> > As far as I know it's highly unlikely. Each world is supposed to have one locked chest for each biome present for a total of 5. You get either the Corruption/Crimson depending on the world too.
> 
> ive beaten plantera and the golem, do you have any idea why my dungeon have no desert chest? i tried making new worlds too but when i checked the world map on TerraMap. there werent any

I'd be pretty certain it does. That's what my issue is about, TerraMap doesn't have an option for showing Locked Desert Chests, even though my world has one it just doesn't appear on TerraMap. As you can see in this image, "Locked Desert Chest" is missing.
![image](https://user-images.githubusercontent.com/25102928/82759041-6f146a00-9de2-11ea-9921-f69252dbbf85.png)

**Comment by TerraTerra77** [comment]
> > > > > > > > hey can i get your world seed? i cant find Desert Tiger Staff. i tried finding it in the golden chest but no luck
> > > > > > > 
> > > > > > > 
> > > > > > > Sure thing.
> > > > > > > 3.3.1.1723894116
> > > > > > 
> > > > > > 
> > > > > > wait... i tried the seed and the took a look at chest near the corruption chest but it isnt desert tiger staff
> > > > > 
> > > > > 
> > > > > I have it set to Master, no idea if that affects whats in the chest.
> > > > 
> > > > 
> > > > is there a chance of not getting a desert chest in the dungeon?
> > > 
> > > 
> > > As far as I know it's highly unlikely. Each world is supposed to have one locked chest for each biome present for a total of 5. You get either the Corruption/Crimson depending on the world too.
> > 
> > 
> > ive beaten plantera and the golem, do you have any idea why my dungeon have no desert chest? i tried making new worlds too but when i checked the world map on TerraMap. there werent any
> 
> I'd be pretty certain it does. That's what my issue is about, TerraMap doesn't have an option for showing Locked Desert Chests, even though my world has one it just doesn't appear on TerraMap. As you can see in this image, "Locked Desert Chest" is missing.
> ![image](https://user-images.githubusercontent.com/25102928/82759041-6f146a00-9de2-11ea-9921-f69252dbbf85.png)

but i tried searching the whole dungeon but i couldnt find one, maybe i should give it one more try

**Comment by jasoncoon** [comment]
This should be fixed in the latest version, 1.4.7: https://terramap.github.io/windows
