### ISSUE TITLE
Hut built with hay blocks and Actuators is invisible in Terramap

### ISSUE THREAD

**Issue by JorgePozoR** [TerraMap/windows#19]
Hi.

I have a Fishing Hut built on a Sky Lake with hay blocks, and I have part of it usually "Switched off" with actuators all around. The part of the hut with Actuators is completely invisible in the current Terramap v1.4.7.

Not sure if this is a "bug" or an intended "feature", and also I cannot say if this comes from earlier versions or if it's caused by 1.4 Terraria update.

Could it be possible to draw the tiles with switched off actuators? (And if they are dimmed or marked as 'Actuated" too it would be a blast :) )

Thanks

**Comment by jasoncoon** [comment]
I don't suppose you could attach your world file to this issue?  If so, I can take a look.  Thanks!

**Comment by JorgePozoR** [comment]
Sure, no problem.
 
[Mundo_de_Kassandra.zip](https://github.com/TerraMap/windows/files/4689225/Mundo_de_Kassandra.zip)

You can see the issue on the lateral walls of the small hut above the sky lake. From the Starting point, just climb up with the rope and move left by the skybridge 'till reaching the lake.

Thanks!

**Comment by jasoncoon** [comment]
This should be fixed in v1.4.9, thanks!  https://terramap.github.io/windows
