### ISSUE TITLE
Some blocks highlights is barely visible 

### ISSUE THREAD

**Issue by fenume** [TerraMap/windows#20]
For example statues(Pigron, Heart, etc). https://i.imgur.com/fkYu3YC.png
Maybe add some outline?

**Comment by jasoncoon** [comment]
Yeah, highlighted tiles with dark colors can be hard to spot.  For these, you can use the Previous and Next Match buttons, or change the highlight overlay color to white, and adjust the slider:

![image](https://user-images.githubusercontent.com/3598755/83334236-b7aca700-a26a-11ea-8378-01110f69876d.png)
