### ISSUE TITLE
Statues are not being highlighted.

### ISSUE THREAD

**Issue by AlphaRage** [TerraMap/windows#21]
Tried finding a sword statue in my world using the client version - latest 1.4.8. Checked a few more worlds and couldn't find one. Tried other statues which I know the placement of, but they are not highlighted either. Not all statues aren't highlighted but >90% are.
Highlighting works in the online version, though.

**Comment by jasoncoon** [comment]
I think this is similar to #20, the highlight can be hard to see on tiles with dark colors.  You can use the Previous and Next Match buttons:

![image](https://user-images.githubusercontent.com/3598755/83334314-3bff2a00-a26b-11ea-9657-99094821ae2d.png)

and you can change the highlight overlay color to white to make it easier to see on dark tiles:

![image](https://user-images.githubusercontent.com/3598755/83334344-75d03080-a26b-11ea-850e-9f4d9036c1cf.png)
