### ISSUE TITLE
Crimson / Hallow Blocks (Set) highlight not functioning

### ISSUE THREAD

**Issue by bwhite94** [TerraMap/windows#22]
In the windows version of TerraMap 1.4.8.15677 sets for Crimson / Hallow Blocks (Set) do not appear to highlight anything.

Selecting the individual block tiles do highlight the blocks for the corresponding biomes, however.

**Comment by jasoncoon** [comment]
Sorry, I can't reproduce this issue.  Have a world you can upload where it's happening?

![image](https://user-images.githubusercontent.com/3598755/83334103-ce9ec980-a269-11ea-98ae-c1aca18c7d7b.png)

![image](https://user-images.githubusercontent.com/3598755/83334082-ad3ddd80-a269-11ea-9131-a0d9817be3c1.png)

![image](https://user-images.githubusercontent.com/3598755/83334129-07d73980-a26a-11ea-9c91-960b02519281.png)

**Comment by bwhite94** [comment]
Please find attached. World was generated with 1.4.0.2 I believe.

[The_Troubled_Mire_of_Shade.zip](https://github.com/TerraMap/windows/files/4706162/The_Troubled_Mire_of_Shade.zip)

**Comment by bwhite94** [comment]
Ah! I just realized something. If you check the option found in the `Blocks` dialog it does not work. The way you mentioned does work, however.

**Comment by bwhite94** [comment]
Reproducible steps:

1. Click the `...` displayed next to the `Blocks` dropdown. 
2. Select Hallow / Crimson Blocks (set). 
3. Click Highlight all.

It works using the `Sets` window menu as well as using the `Blocks` dropdown menu.
