### ISSUE TITLE
Add option to "search in area"

### ISSUE THREAD

**Issue by slitherrr** [TerraMap/windows#23]
One major use I have for this is to find stuff that I've lost in the pile of chests at spawn, but I seem to currently have to search the entire world to find something that I know is actually somewhere in a 50x50 block area. Being able to highlight an area to limit a search to would help this immensely.

If this functionality _does_ exist, and it turns out I'm just dense as mud, then I pre-edit it to say "make this functionality more obvious".

**Comment by jasoncoon** [comment]
You can right-click to set the cursor at a particular location, and then the Next and Previous match buttons will search from there.  :)

**Comment by aawilson** [comment]
Good to know, that does the behavior I'd expect. I was trying left-click for that, it did not occur to me that the other button would produce an action without a context menu.

**Comment by slitherrr** [comment]
Good to know, that does the behavior I'd expect. I was trying left-click for that, it did not occur to me that the other button would produce an action without a context menu.
