### ISSUE TITLE
Many blocks are barely visible - idea

### ISSUE THREAD

**Issue by Neltisen** [TerraMap/windows#25]
Hello,
I've noticed that many blocks are not visible enough when searching for them, while online version works perfectly. Can you add an option for highlighting blocks that are searched like on the webpage (make searched blocks white, while other get dimmed). Thank you for this great tool!

**Comment by jasoncoon** [comment]
Hello! Have you tried the `Highlight Opacity` slider in the toolbar?  That's exactly why I added that.  :)

You can also try changing or inverting the highlight color.

![image](https://user-images.githubusercontent.com/3598755/88927803-96057700-d23d-11ea-9412-038a90413f71.png)
