### ISSUE TITLE
Strange Misplacements, Conversion Hardmode bug

### ISSUE THREAD

**Issue by Dragotiger** [TerraMap/windows#37]
Hello, id like to do an issue regarding to misplacement and map errors for my world and came up as this
![Screenshot 2021-12-05 102343](https://user-images.githubusercontent.com/79160983/144728803-a80e6ba5-68db-4551-9532-fa16a1629b3d.png)
![Screenshot 2021-12-05 102130](https://user-images.githubusercontent.com/79160983/144728804-985117e1-3db8-49f9-a2de-ab4e310715f9.png)

Any help or this may be a bug after all. Besides the Tedit map works fine but the site bugs it out

**Comment by jasoncoon** [comment]
Hey, sorry for the delayed response. I made a change that might fix that. Mind trying again? If it's still happening, can you zip up and upload the world file to this issue?

**Comment by Dragotiger** [comment]
[The_Unsure_Unknown.zip](https://github.com/TerraMap/windows/files/7713110/The_Unsure_Unknown.zip)
This is my world at the moment, Feel free to check it out. Besides I did try agin issues still persisting

**Comment by jasoncoon** [comment]
This should be fixed now.
