### ISSUE TITLE
terramap not loading maps

### ISSUE THREAD

**Issue by Galopoulas** [TerraMap/windows#40]
terramap web and terramap windows lately stopped working on some worlds for no reason.terramap web is stauck on reading world header and terramap windows gives me this error:World file tiles list start is not where it's expected to be. Expected:3306 Actual:3307

**Comment by Galopoulas** [comment]
https://drive.google.com/file/d/1hJHThIJ7Un50v8uTO4ZXEXyodP8vLwoF/view?usp=sharing          UMMMM DONT WORRY ABOUT THE NAME IT IS AN INSIDE JOKE

**Comment by jasoncoon** [comment]
Looks like that world is version 248. TerraMap web and TerraMap Windows v1.4.14 only support the latest version of Terraria (v1.4.4.1). Either load the world in Terraria v1.4.4.1 (which will update it to the latest version), or try downloading and using an older version of TerraMap Windows: https://terramap.github.io/windows.html
