### ISSUE TITLE
Finding Flower Walls and Enchanted Sword tiles

### ISSUE THREAD

**Issue by GaLLeeXY** [TerraMap/windows#8]
I'm trying to find flower walls and enchanted sword tiles so I can find my Enchanted Sword Shrines but every time I try to highlight it it shows there are none in my world

**Comment by jasoncoon** [comment]
Should just be able to search for 'Enchanted Sword' tile:

![image](https://user-images.githubusercontent.com/3598755/82166697-e431ed80-987e-11ea-8d65-1b95818cc17c.png)

**Comment by GaLLeeXY** [comment]
I did what you did in the screenshot but I still can't find it

**Comment by Irredium** [comment]
I am having the same issue

**Comment by jasoncoon** [comment]
Can someone attach their world with this problem to this issue?

**Comment by MattRKing** [comment]
They just won't have one in their world.  It isn't guaranteed in their world gen.
